name: stardpix
description: Are you ready for a decentralized pixels war on Starknet blockchain!
publish_to: "none"

version: 1.1.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  circular_countdown_timer: ^0.2.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hsvcolor_picker: ^1.5.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^7.7.0
  go_router: ^14.6.1
  logging: ^1.3.0
  pixelarticons: ^0.4.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dependency_overrides:  
  http: ^1.0.0
  path: ^1.8.3
  starknet:
    git:
      url: https://github.com/focustree/starknet.dart
      path: packages/starknet
  starknet_provider:
    git:
      url: https://github.com/focustree/starknet.dart
      path: packages/starknet_provider
  wallet_kit:
    git:
      url: https://github.com/focustree/starknet.dart
      path: packages/wallet_kit
      
dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.4
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.4.0
  test: ^1.26.1
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Minecraftia-Regular
      fonts:
        - asset: assets/fonts/Minecraftia-Regular.ttf
  assets:
    - assets/images/
    - lib/application/contracts/
