name: Build Flutter APK

on:
  workflow_dispatch:  
  push:
    branches: [ main ] 

jobs:
  build:
    name: Build APK 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Create .env file
        run: echo "${{ secrets.DOTENV_FILE_TESTNET }}" > .env
        
      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
